import type { ComponentType } from "react";
import type { ImageSourcePropType } from "react-native";
import type { SvgProps } from "react-native-svg";

import {
  SpyCityAmsterdamLocation,
  SpyCityBarcelonaLocation,
  SpyCityBeijingLocation,
  SpyCityBerlinLocation,
  SpyCityCairoLocation,
  SpyCityDubaiLocation,
  SpyCityIstanbulLocation,
  SpyCityLondonLocation,
  SpyCityLosAngelesLocation,
  SpyCityMoscowLocation,
  SpyCityNewYorkLocation,
  SpyCityNizhnyNovgorodLocation,
  SpyCityParisLocation,
  SpyCityPragueLocation,
  SpyCityRioDeJaneiroLocation,
  SpyCityRomeLocation,
  SpyCitySaintPetersburgLocation,
  SpyCitySeoulLocation,
  SpyCitySydneyLocation,
  SpyCityTokyoLocation,
  SpyCityVeniceLocation,
  SpyCityVladivostokLocation,
  SpyEntertainmentAmusementParkLocation,
  SpyEntertainmentAnticafeLocation,
  SpyEntertainmentBowlingLocation,
  SpyEntertainmentCasinoLocation,
  SpyEntertainmentCinemaLocation,
  SpyEntertainmentCircusLocation,
  SpyEntertainmentEscapeRoomLocation,
  SpyEntertainmentIceRinkLocation,
  SpyEntertainmentKaraokeLocation,
  SpyEntertainmentKartingLocation,
  SpyEntertainmentMuseumLocation,
  SpyEntertainmentNightclubLocation,
  SpyEntertainmentPlanetariumLocation,
  SpyEntertainmentRestaurantLocation,
  SpyEntertainmentSpaCenterLocation,
  SpyEntertainmentStadiumLocation,
  SpyEntertainmentTheaterLocation,
  SpyEntertainmentTrampolineCenterLocation,
  SpyEntertainmentWaterParkLocation,
  SpyEntertainmentZooLocation,
  SpyNatureBeachLocation,
  SpyNatureCampingLocation,
  SpyNatureCanyonLocation,
  SpyNatureCaveLocation,
  SpyNatureCoralReefLocation,
  SpyNatureDesertLocation,
  SpyNatureForestLocation,
  SpyNatureGeyserLocation,
  SpyNatureGlacierLocation,
  SpyNatureIslandLocation,
  SpyNatureJungleLocation,
  SpyNatureLakeLocation,
  SpyNatureMeadowLocation,
  SpyNatureMountainsLocation,
  SpyNatureNorthPoleLocation,
  SpyNatureRiverbankLocation,
  SpyNatureSavannaLocation,
  SpyNatureSwampLocation,
  SpyNatureVolcanoLocation,
  SpyNatureWaterfallLocation,
} from "@assets/Spy_game";
import {
  CitiesPackIllustration,
  DcHeroesPackIllustration,
  DomesticAnimalsPackIllustration,
  Dota2HeroesPackIllustration,
  EntertainmentPackIllustration,
  MarvelHeroesPackIllustration,
  NaturePackIllustration,
  ProfessionsPackIllustration,
  SchoolItemsPackIllustration,
  SeaAnimalsPackIllustration,
  TransportPackIllustration,
  WildAnimalsPackIllustration,
  WorkplacesPackIllustration,
} from "@assets/Spy_game/Packs_page";

export const SPY_WORD_IMAGES = {
  "nature-forest": SpyNatureForestLocation,
  "nature-beach": SpyNatureBeachLocation,
  "nature-desert": SpyNatureDesertLocation,
  "nature-mountains": SpyNatureMountainsLocation,
  "nature-cave": SpyNatureCaveLocation,
  "nature-waterfall": SpyNatureWaterfallLocation,
  "nature-volcano": SpyNatureVolcanoLocation,
  "nature-jungle": SpyNatureJungleLocation,
  "nature-swamp": SpyNatureSwampLocation,
  "nature-lake": SpyNatureLakeLocation,
  "nature-island": SpyNatureIslandLocation,
  "nature-glacier": SpyNatureGlacierLocation,
  "nature-canyon": SpyNatureCanyonLocation,
  "nature-savanna": SpyNatureSavannaLocation,
  "nature-coral-reef": SpyNatureCoralReefLocation,
  "nature-geyser": SpyNatureGeyserLocation,
  "nature-meadow": SpyNatureMeadowLocation,
  "nature-riverbank": SpyNatureRiverbankLocation,
  "nature-north-pole": SpyNatureNorthPoleLocation,
  "nature-camping": SpyNatureCampingLocation,
  "entertainment-cinema": SpyEntertainmentCinemaLocation,
  "entertainment-theater": SpyEntertainmentTheaterLocation,
  "entertainment-circus": SpyEntertainmentCircusLocation,
  "entertainment-amusement-park": SpyEntertainmentAmusementParkLocation,
  "entertainment-water-park": SpyEntertainmentWaterParkLocation,
  "entertainment-bowling": SpyEntertainmentBowlingLocation,
  "entertainment-karaoke": SpyEntertainmentKaraokeLocation,
  "entertainment-nightclub": SpyEntertainmentNightclubLocation,
  "entertainment-planetarium": SpyEntertainmentPlanetariumLocation,
  "entertainment-museum": SpyEntertainmentMuseumLocation,
  "entertainment-zoo": SpyEntertainmentZooLocation,
  "entertainment-escape-room": SpyEntertainmentEscapeRoomLocation,
  "entertainment-trampoline-center": SpyEntertainmentTrampolineCenterLocation,
  "entertainment-ice-rink": SpyEntertainmentIceRinkLocation,
  "entertainment-stadium": SpyEntertainmentStadiumLocation,
  "entertainment-casino": SpyEntertainmentCasinoLocation,
  "entertainment-anticafe": SpyEntertainmentAnticafeLocation,
  "entertainment-restaurant": SpyEntertainmentRestaurantLocation,
  "entertainment-spa-center": SpyEntertainmentSpaCenterLocation,
  "entertainment-karting": SpyEntertainmentKartingLocation,
  "cities-london": SpyCityLondonLocation,
  "cities-moscow": SpyCityMoscowLocation,
  "cities-tokyo": SpyCityTokyoLocation,
  "cities-paris": SpyCityParisLocation,
  "cities-new-york": SpyCityNewYorkLocation,
  "cities-rome": SpyCityRomeLocation,
  "cities-berlin": SpyCityBerlinLocation,
  "cities-istanbul": SpyCityIstanbulLocation,
  "cities-dubai": SpyCityDubaiLocation,
  "cities-beijing": SpyCityBeijingLocation,
  "cities-seoul": SpyCitySeoulLocation,
  "cities-sydney": SpyCitySydneyLocation,
  "cities-barcelona": SpyCityBarcelonaLocation,
  "cities-amsterdam": SpyCityAmsterdamLocation,
  "cities-prague": SpyCityPragueLocation,
  "cities-venice": SpyCityVeniceLocation,
  "cities-cairo": SpyCityCairoLocation,
  "cities-rio-de-janeiro": SpyCityRioDeJaneiroLocation,
  "cities-saint-petersburg": SpyCitySaintPetersburgLocation,
  "cities-los-angeles": SpyCityLosAngelesLocation,
  "cities-nizhny-novgorod": SpyCityNizhnyNovgorodLocation,
  "cities-vladivostok": SpyCityVladivostokLocation,
} as const satisfies Record<string, ImageSourcePropType>;

export const SPY_PACK_ILLUSTRATIONS = {
  workplaces: WorkplacesPackIllustration,
  nature: NaturePackIllustration,
  entertainment: EntertainmentPackIllustration,
  transport: TransportPackIllustration,
  cities: CitiesPackIllustration,
  "dota-2-heroes": Dota2HeroesPackIllustration,
  "marvel-cinematic-universe": MarvelHeroesPackIllustration,
  "dc-screen-characters": DcHeroesPackIllustration,
  "domestic-animals": DomesticAnimalsPackIllustration,
  "wild-animals": WildAnimalsPackIllustration,
  "sea-animals": SeaAnimalsPackIllustration,
  "school-items": SchoolItemsPackIllustration,
  professions: ProfessionsPackIllustration,
} as const satisfies Record<string, ComponentType<SvgProps>>;

export type SpyWordImageKey = keyof typeof SPY_WORD_IMAGES;
export type SpyPackIllustrationKey = keyof typeof SPY_PACK_ILLUSTRATIONS;

export function getSpyWordImage(imageKey: string | undefined) {
  if (!imageKey) {
    return undefined;
  }

  return SPY_WORD_IMAGES[imageKey as SpyWordImageKey];
}

export function getSpyPackIllustration(
  illustrationKey: string | undefined,
) {
  if (!illustrationKey) {
    return undefined;
  }

  return SPY_PACK_ILLUSTRATIONS[
    illustrationKey as SpyPackIllustrationKey
  ];
}
